export default function TermsPage() {
  return (
    <div style={{ maxWidth: 800, margin: "0 auto", padding: "80px 24px" }}>
      <p className="section-label">Legal</p>
      <h1
        style={{
          fontSize: 48,
          fontWeight: 800,
          color: "#0A0A0A",
          marginTop: 8,
          marginBottom: 16,
        }}
      >
        Terms of Service
      </h1>
      <p style={{ fontSize: 14, color: "#9CA3AF", marginBottom: 48 }}>
        Last updated: April 6, 2026
      </p>

      {[
        {
          title: "1. Acceptance of Terms",
          content:
            "By accessing or using TravelAI, you agree to be bound by these Terms of Service. If you do not agree, please do not use our service.",
        },
        {
          title: "2. Description of Service",
          content:
            "TravelAI is an AI-powered travel planning platform that generates personalized itineraries using artificial intelligence, knowledge graphs, real-time weather data, currency conversion, and place recommendations. The service is provided 'as is' and itineraries are suggestions, not guarantees.",
        },
        {
          title: "3. User Accounts",
          content:
            "You are responsible for maintaining the confidentiality of your account credentials. You must provide accurate information during registration. You may not share your account with others or create multiple accounts.",
        },
        {
          title: "4. AI-Generated Content",
          content:
            "Itineraries and recommendations are generated by AI and may not always be accurate. Restaurant availability, pricing, halal certification, weather conditions, and currency rates may change. Always verify critical information independently before traveling.",
        },
        {
          title: "5. Acceptable Use",
          content:
            "You agree not to: use the service for any illegal purpose, attempt to access other users' data, overload our servers with excessive requests, reverse-engineer our AI systems, or scrape content from our platform.",
        },
        {
          title: "6. Intellectual Property",
          content:
            "TravelAI and its original content, features, and functionality are owned by TravelAI and are protected by international copyright, trademark, and other intellectual property laws.",
        },
        {
          title: "7. Limitation of Liability",
          content:
            "TravelAI shall not be liable for any indirect, incidental, special, or consequential damages resulting from the use or inability to use our service, including but not limited to travel disruptions, incorrect recommendations, or data loss.",
        },
        {
          title: "8. Changes to Terms",
          content:
            "We reserve the right to modify these terms at any time. Continued use of the service after changes constitutes acceptance of the new terms.",
        },
        {
          title: "9. Contact",
          content:
            "For questions about these terms, contact us at legal@travelai.com.",
        },
      ].map((s) => (
        <div key={s.title} style={{ marginBottom: 32 }}>
          <h2
            style={{
              fontSize: 22,
              fontWeight: 700,
              color: "#0A0A0A",
              marginBottom: 8,
            }}
          >
            {s.title}
          </h2>
          <p style={{ fontSize: 16, color: "#6B7280", lineHeight: 1.7 }}>
            {s.content}
          </p>
        </div>
      ))}
    </div>
  );
}
