"use client";

export async function exportTripPDF(trip) {
    const { jsPDF } = await import("jspdf");
    const doc = new jsPDF();
    const orange = [255, 69, 0];
    const dark = [10, 10, 10];
    const gray = [107, 114, 128];
    let y = 20;

    // Title
    doc.setFontSize(24);
    doc.setTextColor(...orange);
    doc.text("TravelAI", 14, y);
    y += 12;

    doc.setFontSize(18);
    doc.setTextColor(...dark);
    doc.text(trip.title || "Trip Itinerary", 14, y);
    y += 8;

    doc.setFontSize(11);
    doc.setTextColor(...gray);
    doc.text(`Destination: ${trip.destination}`, 14, y);
    y += 6;
    if (trip.budget?.total) doc.text(`Budget: ${trip.budget.currency} ${trip.budget.total}`, 14, y);
    y += 6;
    doc.text(`Status: ${trip.status} | ${trip.aiGenerated ? "AI Generated" : "Manual"}`, 14, y);
    y += 10;

    // Divider
    doc.setDrawColor(240, 240, 240);
    doc.line(14, y, 196, y);
    y += 8;

    // Itinerary
    if (trip.itinerary?.length > 0) {
        trip.itinerary.forEach((day, i) => {
            if (y > 260) { doc.addPage(); y = 20; }

            doc.setFontSize(14);
            doc.setTextColor(...orange);
            doc.text(`Day ${day.day || i + 1}`, 14, y);
            y += 7;

            if (day.weather) {
                doc.setFontSize(9);
                doc.setTextColor(...gray);
                doc.text(`${day.weather.temp || ""}° — ${day.weather.description || ""}`, 14, y);
                y += 6;
            }

            (day.activities || []).forEach((act, j) => {
                if (y > 265) { doc.addPage(); y = 20; }

                doc.setFontSize(11);
                doc.setTextColor(...dark);
                doc.text(`${act.time || ""} ${act.name}`, 20, y);
                y += 5;

                if (act.description) {
                    doc.setFontSize(9);
                    doc.setTextColor(...gray);
                    const lines = doc.splitTextToSize(act.description, 170);
                    doc.text(lines, 20, y);
                    y += lines.length * 4 + 2;
                }

                if (act.cost?.amount) {
                    doc.setFontSize(9);
                    doc.text(`Cost: ${act.cost.currency} ${act.cost.amount}`, 20, y);
                    y += 5;
                }
                y += 3;
            });
            y += 5;
        });
    }

    // Footer
    doc.setFontSize(8);
    doc.setTextColor(...gray);
    doc.text(`Generated by TravelAI — ${new Date().toLocaleDateString()}`, 14, 285);

    doc.save(`${trip.title || "trip"}-itinerary.pdf`);
}
